### ISSUE TITLE
测试页面3 切换到空布局的时候 异常

### ISSUE THREAD

**Issue by yexseven** [yangchong211/YCStateLayout#7]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.ns.yc.ycstatelib.OnRetryListener.onRetry()' on a null object reference
        at com.ns.yc.ycstatelib.StateFrameLayout$3.onClick(StateFrameLayout.java:353)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by yangchong211** [comment]
谢谢关注，可以在更新一下demo，已经修改
